# Generated by Django 5.1.5 on 2025-01-29 05:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BaneficiaryCategory",
            new_name="BeneficiaryCategory",
        ),
    ]
