# Generated by Django 5.1.5 on 2025-01-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0002_rename_baneficiarycategory_beneficiarycategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiarymaster",
            name="count",
            field=models.IntegerField(),
        ),
    ]
