# Generated by Django 5.1.5 on 2025-01-29 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0003_alter_beneficiarymaster_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="beneficiarymaster",
            old_name="icon_name",
            new_name="icon_title",
        ),
        migrations.RemoveField(
            model_name="beneficiarymaster",
            name="title",
        ),
    ]
