# Generated by Django 5.1.5 on 2025-01-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0004_rename_icon_name_beneficiarymaster_icon_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiarymaster",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="beneficiary_images/"
            ),
        ),
    ]
