# Generated by Django 5.1.5 on 2025-01-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0005_beneficiarymaster_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiarymaster",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="beneficiary_images/"
            ),
        ),
    ]
