# Generated by Django 5.1.5 on 2025-01-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0006_alter_beneficiarymaster_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyProgramMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon_title", models.CharField(max_length=255)),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="KeyProgram_images/"
                    ),
                ),
                ("desc", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
