# Generated by Django 5.1.5 on 2025-01-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0007_keyprogrammaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiaryAid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aid_title", models.CharField(max_length=255)),
                ("aid_desc", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
