# Generated by Django 5.1.5 on 2025-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0008_beneficiaryaid"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudiesMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_title", models.CharField(max_length=255)),
                ("case_name", models.CharField(max_length=255)),
                ("case_desc", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
