# Generated by Django 5.1.5 on 2025-01-29 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0009_casestudiesmaster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casestudiesmaster",
            name="case_title",
        ),
    ]
