# Generated by Django 5.1.5 on 2025-01-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0011_latesteventmaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryActivityMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="ActivityGallery_images/"
                    ),
                ),
            ],
        ),
    ]
