# Generated by Django 5.1.5 on 2025-01-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0012_galleryactivitymaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagingTrustee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("managing_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="GalleryActivityMaster",
        ),
    ]
