# Generated by Django 5.1.5 on 2025-01-30 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0013_managingtrustee_delete_galleryactivitymaster"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ManagingTrustee",
        ),
    ]
