# Generated by Django 5.1.5 on 2025-01-30 09:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0016_categorymodel_mastermodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_name", models.CharField(max_length=255, null=True)),
                ("system_value", models.TextField(blank=True, null=True)),
                (
                    "system_img",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="banner/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp", "svg"]
                            )
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("icon", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="kct.systemmaster",
            ),
        ),
        migrations.DeleteModel(
            name="MasterModel",
        ),
    ]
