# Generated by Django 5.1.5 on 2025-01-30 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0017_systemmaster_alter_categorymodel_parent_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ListItem",
            new_name="ListItemCategory",
        ),
        migrations.RenameModel(
            old_name="ManagingListCategory",
            new_name="ManagingListCategoryMaster",
        ),
        migrations.CreateModel(
            name="BeneficiaryAid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiary_aid",
                        to="kct.systemmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeneficiaryMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiary_master",
                        to="kct.systemmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeneficiaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kct.beneficiarymaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseStudiesMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_study_master",
                        to="kct.systemmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeyProgramMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_program_master",
                        to="kct.systemmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LatestEventMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latest_event_master",
                        to="kct.systemmaster",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CategoryModel",
        ),
    ]
