# Generated by Django 5.1.5 on 2025-01-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0018_rename_listitem_listitemcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmaster",
            name="system_titlle",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
