# Generated by Django 5.1.5 on 2025-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0019_systemmaster_system_titlle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemmaster",
            name="system_titlle",
        ),
        migrations.AddField(
            model_name="systemmaster",
            name="system_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
