# Generated by Django 5.1.5 on 2025-01-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0020_remove_systemmaster_system_titlle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmaster",
            name="system_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
