# Generated by Django 5.1.5 on 2025-01-31 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0021_alter_systemmaster_system_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("count", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="beneficiary_images/"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="beneficiarymaster",
            name="system",
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="kct.beneficiary",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BeneficiaryCategory",
        ),
        migrations.DeleteModel(
            name="BeneficiaryMaster",
        ),
    ]
