# Generated by Django 5.1.5 on 2025-01-31 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0022_beneficiary_remove_beneficiarymaster_system_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="beneficiary",
        ),
        migrations.CreateModel(
            name="BeneficiaryMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiary_master",
                        to="kct.systemmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeneficiaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kct.beneficiarymaster",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Beneficiary",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
