# Generated by Django 5.1.5 on 2025-02-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0023_remove_category_beneficiary_beneficiarymaster_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiarycategory",
            name="beneficiary",
        ),
        migrations.RemoveField(
            model_name="beneficiarycategory",
            name="active",
        ),
        migrations.RemoveField(
            model_name="beneficiarycategory",
            name="category",
        ),
        migrations.RemoveField(
            model_name="beneficiarycategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="beneficiarycategory",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="beneficiarycategory",
            name="has_dropdown",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="beneficiarycategory",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="icons/"),
        ),
        migrations.AddField(
            model_name="beneficiarycategory",
            name="name",
            field=models.CharField(default="Default Name", max_length=100),
        ),
        migrations.AddField(
            model_name="beneficiarycategory",
            name="number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="DropdownOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropdown_options",
                        to="kct.beneficiarycategory",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BeneficiaryMaster",
        ),
    ]
