# Generated by Django 5.1.5 on 2025-02-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0024_remove_beneficiarycategory_beneficiary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiarycategory",
            name="icon",
            field=models.FileField(blank=True, null=True, upload_to="icons/"),
        ),
    ]
