# Generated by Django 5.1.5 on 2025-02-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0025_alter_beneficiarycategory_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="footer_logos/"),
                ),
                ("about_text", models.TextField()),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("facebook_link", models.URLField(blank=True, null=True)),
                ("instagram_link", models.URLField(blank=True, null=True)),
                ("twitter_link", models.URLField(blank=True, null=True)),
                ("youtube_link", models.URLField(blank=True, null=True)),
                ("office_timings", models.TextField()),
                ("patients_schedule", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="systemmaster",
            name="icon",
        ),
    ]
