# Generated by Django 5.1.5 on 2025-02-03 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0027_alter_systemmaster_system_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmaster",
            name="system_img",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="banner/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "svg"]
                    )
                ],
            ),
        ),
    ]
