# Generated by Django 5.1.5 on 2025-02-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0029_systemmastercategory_systemmaster_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="KCTEnquireMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
