# Generated by Django 5.1.5 on 2025-02-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0030_kctenquiremaster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kctenquiremaster",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
