# Generated by Django 5.1.5 on 2025-02-15 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0031_alter_kctenquiremaster_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Footer",
        ),
    ]
