# Generated by Django 5.0.6 on 2025-02-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0032_delete_footer"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=255)),
                ("event_description", models.TextField()),
                ("event_img", models.FileField(upload_to="event_images/")),
                ("reactions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
