# Generated by Django 5.0.6 on 2025-02-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0033_eventmaster"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemmaster",
            old_name="active",
            new_name="is_active",
        ),
        migrations.AddField(
            model_name="beneficiaryaid",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="beneficiarycategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="casestudiesmaster",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dropdownoption",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventmaster",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kctenquiremaster",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="keyprogrammaster",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="latesteventmaster",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="listitemcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="managinglistcategorymaster",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
