# Generated by Django 5.0.6 on 2025-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0034_rename_active_systemmaster_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmaster",
            name="time",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
