# Generated by Django 5.0.6 on 2025-02-19 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0035_eventmaster_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmaster",
            name="event_quote",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="EventFeatureMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reality_check", models.CharField(max_length=10000)),
                ("kct_remedy", models.CharField(max_length=10000)),
                ("tasks", models.CharField(max_length=10000)),
                ("monthly_ritual", models.CharField(max_length=10000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kct.eventmaster",
                    ),
                ),
            ],
        ),
    ]
