# Generated by Django 5.0.6 on 2025-02-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0036_eventmaster_event_quote_eventfeaturemaster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventmaster",
            name="event_quote",
        ),
        migrations.AddField(
            model_name="eventfeaturemaster",
            name="event_quote",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
