# Generated by Django 5.0.6 on 2025-02-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0037_remove_eventmaster_event_quote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventfeaturemaster",
            name="event_desc",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
