# Generated by Django 5.0.6 on 2025-02-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0038_eventfeaturemaster_event_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfeaturemaster",
            name="event_desc",
            field=models.TextField(blank=True, max_length=2550),
        ),
        migrations.AlterField(
            model_name="eventfeaturemaster",
            name="event_quote",
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
