# Generated by Django 5.0.6 on 2025-02-19 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0039_alter_eventfeaturemaster_event_desc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventfeaturemaster",
            name="monthly_ritual",
        ),
        migrations.RemoveField(
            model_name="eventfeaturemaster",
            name="tasks",
        ),
    ]
