# Generated by Django 5.0.6 on 2025-02-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0040_remove_eventfeaturemaster_monthly_ritual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmaster",
            name="event_feature",
            field=models.TextField(blank=True, max_length=2550),
        ),
        migrations.AddField(
            model_name="eventmaster",
            name="kct_remedy",
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name="eventmaster",
            name="reality_check",
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
