# Generated by Django 5.0.6 on 2025-02-19 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0042_eventmaster_event_quote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventFeatureMaster",
        ),
    ]
