# Generated by Django 5.0.6 on 2025-02-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0043_delete_eventfeaturemaster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmaster",
            name="event_feature",
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
