# Generated by Django 5.0.6 on 2025-02-19 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0044_alter_eventmaster_event_feature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventmaster",
            name="kct_remedy",
        ),
        migrations.RemoveField(
            model_name="eventmaster",
            name="reality_check",
        ),
    ]
