# Generated by Django 5.0.6 on 2025-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0045_remove_eventmaster_kct_remedy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventmaster",
            name="event_quote",
        ),
    ]
