# Generated by Django 5.1.6 on 2025-02-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0046_remove_eventmaster_event_quote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whypay",
                    models.CharField(
                        choices=[
                            ("zakat", "Zakat"),
                            ("fi-sabilillah", "Fi Sabilillah"),
                            ("sadqa", "Sadqa"),
                            ("interest", "Interest"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "paying_from",
                    models.CharField(
                        choices=[
                            ("personal-account", "Personal Account"),
                            ("official-account", "Official Account"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("fullname", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("pan", models.CharField(blank=True, max_length=20, null=True)),
                ("aadhar", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("company_address", models.TextField(blank=True, null=True)),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("company_pan", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "contact_person_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_person_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
