# Generated by Django 5.1.6 on 2025-02-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0047_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
