# Generated by Django 5.1.6 on 2025-03-03 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0048_donation_payment_status_donation_razorpay_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="aadhar",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="address",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="company_address",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="company_email",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="company_pan",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="company_phone",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="contact_person_name",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="contact_person_phone",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="email",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="fullname",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="pan",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="paying_from",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="whypay",
        ),
    ]
