# Generated by Django 5.1.6 on 2025-03-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0049_remove_donation_aadhar_remove_donation_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmaster",
            name="event_quotes",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
