# Generated by Django 5.1.6 on 2025-03-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0050_eventmaster_event_quotes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Donation",
        ),
        migrations.AddField(
            model_name="dropdownoption",
            name="count",
            field=models.IntegerField(null=True),
        ),
    ]
