# Generated by Django 5.1.6 on 2025-03-04 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0051_delete_donation_dropdownoption_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casestudiesmaster",
            name="system",
        ),
        migrations.RemoveField(
            model_name="keyprogrammaster",
            name="system",
        ),
        migrations.RemoveField(
            model_name="latesteventmaster",
            name="system",
        ),
        migrations.DeleteModel(
            name="BeneficiaryAid",
        ),
        migrations.DeleteModel(
            name="CaseStudiesMaster",
        ),
        migrations.DeleteModel(
            name="KeyProgramMaster",
        ),
        migrations.DeleteModel(
            name="LatestEventMaster",
        ),
    ]
