# Generated by Django 5.1.6 on 2025-03-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0052_remove_casestudiesmaster_system_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmaster",
            name="page_quotes",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
