# Generated by Django 5.1.6 on 2025-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0053_systemmaster_page_quotes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beneficiarycategory",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="dropdownoption",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="beneficiarycategory",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dropdownoption",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
