# Generated by Django 5.1.6 on 2025-03-17 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kct", "0055_alter_beneficiarycategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventmaster",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="kctenquiremaster",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="managinglistcategorymaster",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="systemmaster",
            options={"ordering": ["id"]},
        ),
    ]
