# Generated by Django 4.2 on 2025-04-03 12:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0057_homebannermaster_projectmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtSchemeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govtscheme_title', models.CharField(max_length=255)),
                ('govtscheme_description', models.TextField()),
                ('govtscheme_feature', ckeditor.fields.RichTextField()),
                ('govtscheme_img', models.FileField(upload_to='govtscheme_images/')),
                ('time', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
