# Generated by Django 4.2 on 2025-04-11 10:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0058_govtschememaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaster',
            name='project_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
