# Generated by Django 4.2 on 2025-04-11 10:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0059_alter_projectmaster_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaster',
            name='project_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectmaster',
            name='project_feature',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
