# Generated by Django 4.2 on 2025-04-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0061_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('beneficiaries', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
