# Generated by Django 4.2 on 2025-04-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0062_beneficiarydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='logos/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
