# Generated by Django 4.2 on 2025-04-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0063_partnerlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlogo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
