# Generated by Django 4.2 on 2025-04-15 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0064_alter_partnerlogo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlogo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerlogo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partnerlogo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
