# Generated by Django 4.2 on 2025-04-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0065_partnerlogo_created_at_partnerlogo_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerlogo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partnerlogo',
            name='updated_at',
        ),
    ]
