# Generated by Django 4.2 on 2025-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0066_remove_partnerlogo_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_img', models.FileField(upload_to='gallery/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
