# Generated by Django 4.2 on 2025-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0067_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
