# Generated by Django 4.2 on 2025-04-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0068_galleryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarydata',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
