# Generated by Django 4.2 on 2025-07-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0069_alter_beneficiarydata_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiarycategory',
            name='has_dropdown',
        ),
        migrations.RemoveField(
            model_name='beneficiarycategory',
            name='icon',
        ),
    ]
