# Generated by Django 4.2 on 2026-02-09 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0070_remove_beneficiarycategory_has_dropdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_type', models.CharField(choices=[('ZAKAT', 'Zakat'), ('SADAQAH', 'Sadaqah'), ('FI_SABILILLAH', 'Fi Sabilillah'), ('INTEREST', 'Interest'), ('OTHERS', 'Others')], default='SADAQAH', max_length=20)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('payment_session_id', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
