# Generated by Django 4.2 on 2026-02-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0071_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
