# Generated by Django 4.2 on 2026-02-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0073_donation_message_donation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
